---
apiVersion: v1
kind: Service
metadata:
  name: addressbook-load-balancer
  labels:
    service: addressbook-load-balancer
spec:
  selector:
    app: addressbook
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31444
    protocol: TCP
